import { createFileRoute, Link } from "@tanstack/react-router";
import roasteryImage from "@/assets/jowam-roastery.jpg";
import originImage from "@/assets/jowam-origin-kenya.jpg";
import baristaImage from "@/assets/jowam-barista.jpg";
import cuppingImage from "@/assets/jowam-cupping-table.jpg";
import productsImage from "@/assets/jowam-bags-black-coffee.jpg";
import { Button } from "@/components/ui/button";
import { CoffeeProduct, Image, SectionIntro, TextLink } from "@/components/jowam/editorial";
import { coffees } from "@/data/jowam";

export const Route = createFileRoute("/coffee")({ head: () => ({ meta: [
  { title: "Our Coffee | Jowam Coffee Roasters" }, { name: "description", content: "Discover Jowam’s approach to Kenyan specialty coffee, thoughtful sourcing, processing, roasting and flavour." },
  { property: "og:title", content: "Our Coffee | Jowam Coffee Roasters" }, { property: "og:description", content: "Kenyan coffee, thoughtfully sourced and roasted by Jowam." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/coffee" }, { name: "twitter:card", content: "summary_large_image" },
], links: [{ rel: "canonical", href: "/coffee" }] }), component: CoffeePage });

const principles = [{ n: "01", title: "Origin", body: "Where coffee begins — with place, people and growing conditions." }, { n: "02", title: "Quality", body: "Coffee selected for clarity, character and a delicious cup." }, { n: "03", title: "Roasting", body: "A careful approach that lets each coffee speak for itself." }, { n: "04", title: "Brewing", body: "Prepared with attention, whether at the café or at home." }];
const processes = [{ title: "Washed", body: "Fruit is removed before drying, often creating a clean, bright and articulate cup." }, { title: "Natural", body: "Coffee dries inside the fruit, often bringing deeper sweetness and fruit-forward character." }, { title: "Honey", body: "Some fruit remains through drying, balancing clarity with rounded sweetness." }, { title: "Experimental", body: "Careful variations in fermentation can reveal unexpected flavour. Every method needs context." }];
const flavours = [{ title: "Bright & fruity", notes: "Citrus · Berries · Floral", tone: "bg-cherry text-ink-foreground" }, { title: "Sweet & balanced", notes: "Honey · Caramel · Stone fruit", tone: "bg-paper-deep text-foreground" }, { title: "Rich & comforting", notes: "Chocolate · Nuts · Cocoa", tone: "bg-olive text-ink-foreground" }];

function CoffeePage() { return <main>
  <section className="relative min-h-[78svh] overflow-hidden bg-ink text-ink-foreground"><Image src={roasteryImage} alt="Coffee roasting in progress at a drum roaster" width={1600} height={1072} priority sizes="100vw" className="absolute inset-0" /><div className="absolute inset-0 bg-ink/55" /><div className="relative mx-auto flex min-h-[78svh] max-w-screen-2xl flex-col justify-end px-5 py-14 sm:px-8 lg:px-12"><p className="eyebrow text-ink-foreground/70">From green coffee to your cup</p><h1 className="mt-4 max-w-5xl font-display text-7xl leading-[0.88] sm:text-8xl lg:text-[7rem]">Coffee,<br /><em>our way.</em></h1><p className="mt-7 max-w-lg text-lg leading-7 text-ink-foreground/75">Kenyan coffee. Thoughtfully sourced. Roasted by us.</p><div className="mt-8"><Button asChild variant="hero" size="lg"><Link to="/shop">Shop coffee</Link></Button></div></div></section>
  <nav className="sticky top-20 z-40 border-b border-border bg-background/95 backdrop-blur" aria-label="Coffee page sections"><div className="mx-auto flex max-w-screen-2xl gap-7 overflow-x-auto px-5 py-4 sm:px-8 lg:px-12">{[["Our coffee","specialty"],["The roastery","roastery"],["Sourcing","origin"],["Brew guides","brewing"],["Coffee experiences","experiences"]].map(([label,id]) => <a key={id} href={`#${id}`} className="shrink-0 text-xs font-semibold uppercase tracking-[0.08em]">{label}</a>)}</div></nav>

  <section id="specialty" className="mx-auto max-w-screen-2xl scroll-mt-36 px-5 py-24 sm:px-8 md:py-32 lg:px-12"><SectionIntro eyebrow="Specialty, made simple" title="Better coffee begins long before the first sip." body="Specialty coffee is selected for quality and handled with care from origin to brewing. The idea is simple: protect what makes the coffee distinctive, then make it delicious and welcoming." /><div className="mt-16 grid border-t border-border md:grid-cols-4">{principles.map((p) => <article key={p.n} className="border-b border-border py-7 md:border-r md:px-6 md:first:pl-0 md:last:border-r-0"><p className="text-xs text-cherry">{p.n}</p><h3 className="mt-8 font-display text-3xl">{p.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{p.body}</p></article>)}</div></section>

  <section id="origin" className="scroll-mt-36 bg-paper-deep"><div className="mx-auto grid max-w-screen-2xl lg:grid-cols-[1.1fr_0.9fr]"><div className="min-h-[34rem]"><Image src={originImage} alt="Ripe coffee cherries being selected in the Kenyan highlands" width={1600} height={1072} /></div><div className="flex flex-col justify-center px-5 py-20 sm:px-8 lg:px-14"><p className="eyebrow">Coffee from Kenya</p><h2 className="mt-4 font-display text-6xl leading-[0.95]">Place shapes flavour.</h2><p className="mt-6 leading-7 text-muted-foreground">Elevation, variety, soil, rainfall and processing all leave their mark. Kenya’s coffee landscapes can produce remarkable clarity, sweetness and fruit character.</p><p className="mt-5 text-xs text-cherry">Nyeri, Kirinyaga and Embu are representative regions only; they do not imply current Jowam sourcing relationships.</p><div className="mt-9 flex gap-3 text-sm"><span className="border-t border-foreground/30 pt-3">Nyeri</span><span className="border-t border-foreground/30 pt-3">Kirinyaga</span><span className="border-t border-foreground/30 pt-3">Embu</span></div></div></div></section>

  <section className="mx-auto grid max-w-screen-2xl gap-12 px-5 py-24 sm:px-8 md:py-32 lg:grid-cols-[0.75fr_1.25fr] lg:px-12"><div><p className="eyebrow">Producer stories</p><h2 className="mt-4 font-display text-5xl leading-none">Every coffee belongs to someone, and somewhere.</h2><p className="mt-6 leading-7 text-muted-foreground">This reusable story format is ready for verified Jowam relationships once supplied. No farm, cooperative or producer relationship is claimed here.</p></div><div className="border-y border-border py-7"><p className="text-xs uppercase text-cherry">Representative profile</p><dl className="mt-7 grid grid-cols-2 gap-y-7 text-sm sm:grid-cols-4"><div><dt className="text-muted-foreground">Producer</dt><dd className="mt-1">To be confirmed</dd></div><div><dt className="text-muted-foreground">Region</dt><dd className="mt-1">Kenya — placeholder</dd></div><div><dt className="text-muted-foreground">Altitude</dt><dd className="mt-1">To be confirmed</dd></div><div><dt className="text-muted-foreground">Process</dt><dd className="mt-1">To be confirmed</dd></div></dl><p className="mt-8 max-w-2xl font-display text-3xl leading-snug">A future home for the people, decisions and landscape behind each Jowam coffee.</p></div></section>

  <section className="bg-paper-deep py-24 md:py-32"><div className="mx-auto max-w-screen-2xl px-5 sm:px-8 lg:px-12"><SectionIntro eyebrow="Same fruit. Different journey." title="Processing changes the cup." body="How coffee fruit is handled after picking can shape clarity, sweetness, body and aroma. Here is the short version." /><div className="mt-14 grid gap-x-10 gap-y-8 md:grid-cols-2">{processes.map((p,i) => <article key={p.title} className="grid grid-cols-[auto_1fr] gap-5 border-t border-foreground/25 pt-5"><span className="font-display text-2xl">0{i+1}</span><div><h3 className="font-display text-3xl">{p.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{p.body}</p></div></article>)}</div></div></section>

  <section id="roastery" className="scroll-mt-36 bg-ink text-ink-foreground"><div className="mx-auto max-w-screen-2xl"><div className="aspect-[16/7] min-h-[25rem] overflow-hidden"><Image src={roasteryImage} alt="Freshly roasted coffee entering a cooling tray" width={1600} height={1072} sizes="100vw" /></div><div className="grid gap-8 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_0.8fr] lg:px-12"><h2 className="font-display text-7xl leading-[0.88] sm:text-8xl">Roasted<br /><em>here.</em></h2><div><p className="text-lg leading-8 text-ink-foreground/75">Different coffees behave differently. We roast to express each coffee’s individual character — not to force every origin into the same idea of light, medium or dark.</p><p className="mt-6 text-xs uppercase text-ink-foreground/45">Specific roastery details to be confirmed</p></div></div></div></section>

  <section className="mx-auto max-w-screen-2xl px-5 py-24 sm:px-8 md:py-32 lg:px-12"><SectionIntro eyebrow="Find your cup" title="Start with flavour." body="You do not need a tasting vocabulary to know what you enjoy. Choose the direction that sounds good." /><div className="mt-12 grid md:grid-cols-3">{flavours.map((f) => <article key={f.title} className={`flex min-h-72 flex-col justify-between p-8 ${f.tone}`}><h3 className="font-display text-4xl">{f.title}</h3><p className="text-sm">{f.notes}</p></article>)}</div></section>

  <section className="bg-paper-deep"><div className="mx-auto max-w-screen-2xl px-5 py-24 sm:px-8 md:py-32 lg:px-12"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><SectionIntro eyebrow="Currently roasting" title="Meet the coffees." body="Representative coffees, tasting notes and prices for this first design iteration." /><TextLink to="/shop">Shop all coffee</TextLink></div><div className="mt-12 grid gap-10 md:grid-cols-3">{coffees.map((coffee) => <CoffeeProduct key={coffee.name} coffee={coffee} />)}</div></div></section>

  <section id="brewing" className="mx-auto grid max-w-screen-2xl scroll-mt-36 gap-10 px-5 py-24 sm:px-8 lg:grid-cols-[1.2fr_0.8fr] lg:px-12"><div className="aspect-[4/3] overflow-hidden"><Image src={productsImage} alt="A cup of black coffee beside bags of Jowam coffee and roasted beans" width={870} height={470} /></div><div className="flex flex-col justify-center"><p className="eyebrow">Brewing</p><h2 className="mt-4 font-display text-5xl">A good coffee, your way.</h2><div className="mt-7 grid grid-cols-2 gap-3 border-y border-border py-5 text-sm"><span>Espresso</span><span>V60</span><span>Aeropress</span><span>French press</span></div><p className="mt-6 leading-7 text-muted-foreground">Future brew guides will make each method clear and useful without turning coffee into homework.</p></div></section>

  <section className="bg-paper-deep"><div className="mx-auto grid max-w-screen-2xl lg:grid-cols-2"><div className="min-h-[34rem]"><Image src={baristaImage} alt="A barista pouring a coffee in the café" width={1200} height={1504} /></div><div className="flex flex-col justify-center px-5 py-20 sm:px-8 lg:px-14"><p className="eyebrow">Coffee at the café</p><h2 className="mt-4 font-display text-6xl leading-none">Taste it before you take it home.</h2><p className="mt-6 leading-7 text-muted-foreground">Jowam coffees meet people at the café. Ask the barista what is currently on espresso or filter, then discover what you enjoy.</p><div className="mt-8"><TextLink to="/menu">View menu</TextLink></div></div></div></section>

  <section id="experiences" className="mx-auto grid max-w-screen-2xl scroll-mt-36 gap-10 px-5 py-24 sm:px-8 md:py-32 lg:grid-cols-[0.8fr_1.2fr] lg:px-12"><div className="flex flex-col justify-center"><p className="eyebrow">Go deeper</p><h2 className="mt-4 font-display text-6xl">Coffee is better shared.</h2><p className="mt-6 leading-7 text-muted-foreground">Cuppings, roastery visits and coffee education create space to taste, compare and ask questions.</p><div className="mt-8"><TextLink to="/experiences">Explore experiences</TextLink></div></div><div className="aspect-[4/3] overflow-hidden"><Image src={cuppingImage} alt="Cupping bowls set out on a table for a Jowam coffee tasting" width={868} height={980} /></div></section>

  <section className="border-t border-border"><div className="mx-auto max-w-screen-2xl px-5 py-24 sm:px-8 lg:px-12"><SectionIntro eyebrow="From the journal" title="Stories for curious drinkers." /><div className="mt-12 grid gap-8 md:grid-cols-3">{["Why Kenyan coffee tastes the way it does","Washed vs natural coffee","How we roast at Jowam"].map((title,i) => <article key={title} className="border-t border-border pt-5"><p className="text-xs uppercase text-muted-foreground">Future article · 0{i+1}</p><h3 className="mt-12 font-display text-3xl leading-tight">{title}</h3><p className="mt-4 text-sm text-cherry">Journal coming later</p></article>)}</div></div></section>
</main>; }
