/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoffeeRouteImport } from './routes/coffee'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrderRouteImport } from './routes/order'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as ApiV1ImagesDriveIdRouteImport } from './routes/api.v1.images.$driveId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeRoute = CoffeeRouteImport.update({
  id: '/coffee',
  path: '/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ImagesDriveIdRoute = ApiV1ImagesDriveIdRouteImport.update({
  id: '/api/v1/images/$driveId',
  path: '/api/v1/images/$driveId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coffee': typeof CoffeeRoute
  '/experiences': typeof ExperiencesRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/our-story': typeof OurStoryRoute
  '/shop': typeof ShopRoute
  '/visit': typeof VisitRoute
  '/wholesale': typeof WholesaleRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/v1/images/$driveId': typeof ApiV1ImagesDriveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coffee': typeof CoffeeRoute
  '/experiences': typeof ExperiencesRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/our-story': typeof OurStoryRoute
  '/shop': typeof ShopRoute
  '/visit': typeof VisitRoute
  '/wholesale': typeof WholesaleRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/v1/images/$driveId': typeof ApiV1ImagesDriveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coffee': typeof CoffeeRoute
  '/experiences': typeof ExperiencesRoute
  '/menu': typeof MenuRoute
  '/order': typeof OrderRoute
  '/our-story': typeof OurStoryRoute
  '/shop': typeof ShopRoute
  '/visit': typeof VisitRoute
  '/wholesale': typeof WholesaleRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/v1/images/$driveId': typeof ApiV1ImagesDriveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coffee'
    | '/experiences'
    | '/menu'
    | '/order'
    | '/our-story'
    | '/shop'
    | '/visit'
    | '/wholesale'
    | '/product/$handle'
    | '/api/v1/images/$driveId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coffee'
    | '/experiences'
    | '/menu'
    | '/order'
    | '/our-story'
    | '/shop'
    | '/visit'
    | '/wholesale'
    | '/product/$handle'
    | '/api/v1/images/$driveId'
  id:
    | '__root__'
    | '/'
    | '/coffee'
    | '/experiences'
    | '/menu'
    | '/order'
    | '/our-story'
    | '/shop'
    | '/visit'
    | '/wholesale'
    | '/product/$handle'
    | '/api/v1/images/$driveId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoffeeRoute: typeof CoffeeRoute
  ExperiencesRoute: typeof ExperiencesRoute
  MenuRoute: typeof MenuRoute
  OrderRoute: typeof OrderRoute
  OurStoryRoute: typeof OurStoryRoute
  ShopRoute: typeof ShopRoute
  VisitRoute: typeof VisitRoute
  WholesaleRoute: typeof WholesaleRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ApiV1ImagesDriveIdRoute: typeof ApiV1ImagesDriveIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee': {
      id: '/coffee'
      path: '/coffee'
      fullPath: '/coffee'
      preLoaderRoute: typeof CoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/images/$driveId': {
      id: '/api/v1/images/$driveId'
      path: '/api/v1/images/$driveId'
      fullPath: '/api/v1/images/$driveId'
      preLoaderRoute: typeof ApiV1ImagesDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoffeeRoute: CoffeeRoute,
  ExperiencesRoute: ExperiencesRoute,
  MenuRoute: MenuRoute,
  OrderRoute: OrderRoute,
  OurStoryRoute: OurStoryRoute,
  ShopRoute: ShopRoute,
  VisitRoute: VisitRoute,
  WholesaleRoute: WholesaleRoute,
  ProductHandleRoute: ProductHandleRoute,
  ApiV1ImagesDriveIdRoute: ApiV1ImagesDriveIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
